.husky/pre-push, package.json, yarn.lock
Gives a friendly reminder to run the e2e ZKP test locally on each push using husky and git hooks.
=> add git hook on push

README.md, circuits/base64.circom, circuits/bigint.circom, circuits/bigint_func.circom, circuits/body_hash_regex.circom, circuits/dkim_header_regex.circom, circuits/email.circom, circuits/extract.circom, circuits/fp.circom, circuits/regex_helpers.circom, circuits/rsa.circom, circuits/sha.circom, circuits/sha256general.circom, circuits/sha256partial.circom, circuits/twitter_reset_regex.circom, circuits/utils.circom, dizkus-scripts/1_compile.sh, docs/README.md, regex_to_circom/gen.py, regex_to_circom/lexical.js, regex_to_circom/regex_to_dfa.js
Parse regexes better with respect to printing, editing, and converting raw regex to DFA-parsable regex with a smaller grammar.
DONE
1) Split files so abstractions within lexical are clearer
2) Fix min-dfa UI to display with our edited lexical.js that also has escaped characters (https://zkregex.com)
TODO
3) Upstream changes to zk-regex
=> updated lexical to have some more parsing fns

src/helpers/dkim/tools.js
* The current Google DNS fetch script isnt compatible with emails that have >1 DKIM signatures
* In tools.js, the script previously extracted `out.Answer[0].data` which assumes that the public key is in the first element in the array
* For certain domains such as Venmo and Coinbase, there are 2 DKIMs and so 2 elements in the array response. The valid public key is in that second element
* This PR updates the logic to `out.Answer[out.Answer.length - 1].data` and got everything to work. Not sure if theres any more edge cases 
* For example this is the diff between [twitter](https://dns.google/resolve?name=dkim-201406._domainkey.twitter.com&type=TXT) fetch and [venmo](https://dns.google/resolve?name=224i4yxa5dv7c2xz3womw6peuasteono._domainkey.amazonses.com&type=TXT) or …
=> fix: fetch DNS public key correctly when there's multiple DKIM sig

packages/circuits/email-verifier.circom, packages/circuits/package.json, packages/circuits/tests/no-body-hash.test.circom, packages/circuits/tests/no-body-hash.test.ts, packages/helpers/src/input-helpers.ts, packages/twitter-verifier-circuits/helpers/generate-inputs.ts
- Ignore `body_hash_idx` when `ignore_body_hash_check` is true
- Add circom tests when `ignore_body_hash_check` is `true`
- Make `sha[256]` a output signal
=> Circom improvements

packages/circuits/helpers/base64.circom, packages/circuits/tests/base64-test.circom, packages/circuits/tests/base64.test.ts
Assert that input to base64lookup is within the range of valid ASCII characters.
=> fix: assert error when using invalid base64 chars

packages/contracts/utils/StringUtils.sol
Add a default convertPackedBytesToString(uint256[] memory packedBytes) function that automatically autofills max and packsize based on full, 31-byte packed bytes. Also fix the bug where 7 was hardcoded into the max size, which bugged fully packed packedBytes.
=> add string utils to have packsize improvements from zkp2p

packages/helpers/package.json, packages/helpers/src/dkim/body/index.ts, packages/helpers/src/dkim/body/relaxed.ts, packages/helpers/src/dkim/body/simple.ts, packages/helpers/src/dkim/dkim-verifier.ts, packages/helpers/src/dkim/header/index.ts, packages/helpers/src/dkim/header/relaxed.ts, packages/helpers/src/dkim/header/simple.ts, packages/helpers/src/dkim/index.ts, packages/helpers/src/dkim/message-parser.ts, packages/helpers/src/dkim/parse-dkim-headers.ts, packages/helpers/src/dkim/tools.ts, yarn.lock
Closes #131
- Migrate js files under helpers/src/dkim to ts
- Add @types to package.json
- Update yarn.lock
- Replace deprecated Buffer's `slice()` with `subarray()`
=> feat: migrate js files to ts

packages/helpers/src/zkp.ts, packages/twitter-verifier-app/pages/MainPage.tsx
Retry download N times.
If the download still fails, cancel the process and display "Error downloading proof files".
Fixes #102
https://github.com/zkemail/zk-email-verify/assets/667227/13e8f95e-82c6-4052-b01f-3d4209302f42
=> Retry download, cancel and notify user on fail

packages/circuits/email-verifier.circom, packages/circuits/helpers/extract.circom, packages/circuits/helpers/utils.circom, packages/circuits/tests/email-verifier.test.ts
Asserts that input padded header and body only contain 0's.
=> Assert valid padding

packages/helpers/package.json, packages/helpers/src/dkim/arc.ts, packages/helpers/src/dkim/index.ts, packages/helpers/tests/__mocks__/localforage.ts, packages/helpers/tests/dkim.test.ts, packages/helpers/tests/test-data/email-body-tampered.eml, packages/helpers/tests/test-data/email-different-domain.eml, packages/helpers/tests/test-data/email-good.eml, packages/helpers/tests/test-data/email-invalid-domain.eml, packages/helpers/tests/test-data/email-invalid-selector.eml
- Add reason for DKIM failure
- Add tests for DKIM signature check (helpers package)
- Refactor ARC revert handling
=> Add DKIM tests

docs/zk-email-docs/UsageGuide/README.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
Mention the issue number that your changes are addressing. Use the format "Fixes #<issue number>" to automatically link your pull request to the relevant issue.
documentation update. Added -O0 flag to the compilation step
=> add simplification flags to usage guide

packages/contracts/DKIMRegistry.sol, packages/contracts/README.md, packages/contracts/foundry.toml, packages/contracts/package.json, packages/contracts/remappings.txt, packages/contracts/test/DKIMRegistry.t.sol, yarn.lock
Needed for ether-email-auth to work for recovery. Adds a unit test for dkim registry. Note that the interface for DKIMRegistry now needs an initializer of the owner passed in on initialization. I haev major version bumped to 6.0.0 for this. Note that we should add this foundry test into the CI on Github.
=> Oz5 Update for Contracts for AA Compatibility

packages/helpers/package.json, yarn.lock
I had some issue about grpc and node-gyp during installing the @zk-email/helper(with `pnpm add`). After analysis, [pki](https://www.npmjs.com/package/pki) doesn't be imported and I can't find the source code for the lib.
Remove unused dependency.
=> remove unuse dependency

packages/circuits/utils/regex.circom
When the `startIndex` in `SelectRegexReveal` was large enough, `GreaterThan(bitLength)` at the line 36 of `regex.circom` failed because its second argument `startIndex + maxRevealLen - 1` was larger than `bitLength=log2Ceil(maxArrayLen)` bits.
This bug made tests in [ether-email-auth](https://github.com/zkemail/ether-email-auth/tree/d0b0c9307f2e1babe747657c5708bd2974aa1a27/packages/circuits/tests) failed.
I fixed that definition of `bitLength` to `bitLength=log2Ceil(maxArrayLen + maxRevealLen - 1)`, allowing the maximum length of the second argument.
I confirmed that circuit tests in zk-email-verify and the above tests in ether-email-auth passed on my local environment after this fix.
=> [BUG FIX] Fix SelectRegexReveal

packages/circuits/tests/splitBytesToWords.test.ts, packages/circuits/tests/test-circuits/splitBytesToWords-test.circom, packages/circuits/utils/bytes.circom
Add SplitBytesToWords circom template to bytes.circom helper file.
The introduced circuit allows to split an array of bytes into an array of words, which is useful for casting a message or modulus before RSA verification.
=> add SplitBytesToWords circuit to bytes.circom

packages/circuits/email-verifier.circom, packages/circuits/helpers/remove-soft-line-breaks.circom, packages/circuits/tests/email-verifier.test.ts, packages/circuits/tests/remove-soft-line-breaks.test.ts, packages/circuits/tests/test-circuits/email-verifier-no-body-test.circom, packages/circuits/tests/test-circuits/email-verifier-test.circom, packages/circuits/tests/test-circuits/email-verifier-with-soft-line-breaks-test.circom, packages/circuits/tests/test-circuits/remove-soft-line-breaks-test.circom, packages/circuits/tests/test-emails/lorem_ipsum.eml, packages/circuits/utils/array.circom, packages/circuits/utils/hash.circom, packages/helpers/src/input-generators.ts
This PR adds a helper circuit which proves the removal of soft line breaks introduced in Quoted Printable Encoding. Aims to resolve #187.
=> Feat: Circuit for Removing the Quoted Printable Encoding in Email Body

packages/circuits/helpers/remove-soft-line-breaks.circom, packages/circuits/tests/remove-soft-line-breaks.test.ts
This PR includes a bug fix in the `remove-soft-line-breaks` template where the template could not handle soft-line breaks at the beginning of the email body.
=> fix: remove-soft-line-break at the beginning

packages/helpers/src/lib/mailauth/DoH.ts, packages/helpers/src/lib/mailauth/tools.ts
For some emails, the DKIM public key is not stored TXT record directly in `selector._domainkey.domain`, but instead points to a CNAME.
For example, when retrieving the DKIM public key for the following domain: `protonmail._domainkey.proton.me`, we first need to resolve the CNAME for this domain: `protonmail.domainkey.drfeyjwh4gwlal4e2rhajsytrp6auv2nhenecpzigu7muak6lw6ya.domains.proton.ch`.
However, using the "dns" npm package, the CNAME cannot be resolved.
With this update, all DNS resolutions will be performed using google DNS-over-HTTPS (DoH).
=> Fixed a bug in retrieving the DKIM public key

packages/circuits/lib/fp.circom, packages/circuits/tests/fp-mul.test.ts, packages/circuits/tests/test-circuits/fp-mul-test-range-check.circom, packages/circuits/tests/test-circuits/fp-mul-test.circom, packages/circuits/tests/test-circuits/fp-mul-test2.circom
This PR fixes a potential attack vector in the `FpMul` circom template such that a remainder `r` larger than or equal to a module `p` can pass constraints.
Example: `a=4`, `b=4`, `p=5`, `q=2`, `r=6`.
To fix this vulnerability, I added a range check `r < p` to the `FpMul` circom template.
=> Add r < p check to FpMul

packages/circuits/package.json, packages/contracts/UserOverrideableDKIMRegistry.sol, packages/contracts/package.json, packages/contracts/test/UserOverrideableDKIMRegistry.t.sol, packages/helpers/package.json
I added a function that allows only the owner of the user overridable dkim registry to change the main authorizer.
=> Add a function to change the main authorizer to Useroverridable DKIM registry.

packages/circuits/tests/poseidon-modular.test.ts, packages/circuits/tests/test-circuits/poseidon-modular-test.circom, packages/helpers/src/hash.ts
This PR includes a test for the `PoseidonModular` template, which will help others to utilise this template elsewhere.
=> Feat: Added Poseidon Modular Tests

packages/circuits/tests/clean-email-address.test.ts, packages/circuits/tests/test-circuits/clean-email-address-test.circom, packages/circuits/utils/email.circom
This PR adds a utility template to clean up emails of the form `name.surname+alias@email.com` to `namesurname@email.com`.
=> feat: added CleanEmailAddress template

packages/helpers/package.json, packages/helpers/src/dkim/index.ts, packages/helpers/src/lib/mailauth/dkim-verifier.ts, packages/helpers/tests/dkim.test.ts, packages/helpers/tests/test-data/email-bodyless.eml
This PR adds an optional flag for skipBodyHash and tests for pass on tampered body as well as bodyless emails with skipBodyHash=true.
=> Add skipBodyHash check flag in verifyDkimSignature function

packages/helpers/src/dkim/dns-over-http.ts
- fix regex in DNS query over https
-  tries cloudflare dns query before failing
=> fix: regex dns query
